import Foundation

/// Generates a "recreation sheet" — a Markdown document listing each
/// Camera Raw slider value. For editors that don't read XMP presets
/// natively (e.g. Pixelmator Pro), the user opens this next to their
/// editor and dials in each value manually.
///
/// Output format is intentionally simple Markdown so it renders well
/// in any text editor, in GitHub, or pasted into a note.
enum RecreationSheetWriter {

    /// Build the recreation sheet as a String. Caller writes it to disk.
    static func make(name: String, preset: DerivedPreset) -> String {
        let timestamp = ISO8601DateFormatter().string(from: Date())
        return """
        # Preset Recreation: \(name)

        _Generated by RawDeck Presetter on \(timestamp)._

        These values approximate the look of the reference image.
        Fine-tune to taste — single-image analysis is approximate.

        ## Basic Panel

        | Slider | Value | Notes |
        | --- | --- | --- |
        | Exposure     | \(formatEV(preset.exposure)) EV | |
        | Contrast     | \(format(preset.contrast)) | |
        | Highlights   | \(format(preset.highlights)) | Negative = recover |
        | Shadows      | \(format(preset.shadows)) | |
        | Whites       | \(format(preset.whites)) | |
        | Blacks       | \(format(preset.blacks)) | |
        | Texture      | 0  | Not inferred from single image |
        | Clarity      | 0  | Not inferred from single image |
        | Dehaze       | 0  | Not inferred from single image |
        | Vibrance     | \(format(preset.vibrance)) | |
        | Saturation   | \(format(preset.saturation)) | |

        ## White Balance

        | Slider | Value |
        | --- | --- |
        | Temperature | \(format(preset.temperature)) |
        | Tint        | \(format(preset.tint)) |

        ## Detail (Sharpening / Noise Reduction)

        Sharpening and noise reduction can't be inferred from a
        finished image. Suggested starting values:

        | Setting | Value |
        | --- | --- |
        | Sharpening Amount | 25 |
        | Sharpening Radius | 1.0 |
        | Sharpening Detail | 25 |
        | Luminance NR      | 0–25 |
        | Color NR          | 25 |

        ## HSL / Color Grading / Calibration

        Not inferred from a single reference image. Adjust manually
        based on the specific look you want.

        ---

        ## How to apply in Pixelmator Pro

        1. Open your RAW in Pixelmator Pro.
        2. In the **Color Adjustments** tool, dial in each value above.
           Pixelmator's sliders go from −100 to +100 (matching Camera
           Raw's range for most controls). Exposure in Pixelmator is
           also in EV stops.
        3. Once you're happy with the look, save it as a Pixelmator
           preset (Format → Save As Preset) so you can apply it with
           one click to other RAWs.
        4. For batch application, use Pixelmator's File → Batch
           processing feature with the saved preset.

        ## How to apply in Photoshop Camera Raw

        1. Open the exported `.xmp` file (the other export option) in
           Photoshop via *File → Open* — Camera Raw will read it as
           a preset.
        2. Or import it via *Filter → Camera Raw Filter → Presets →
           Import*.

        ## How to apply in Lightroom Classic

        1. Develop module → Presets panel.
        2. Click `+` → Import Presets.
        3. Select the `.xmp` file.
        """
    }

    /// Format a signed Double with 2 decimal places, e.g. `+12.50` or `−3.00`.
    private static func format(_ d: Double) -> String {
        if abs(d) < 0.005 { return "0" }
        let sign = d > 0 ? "+" : ""  // negatives already have a minus
        return String(format: "\(sign)%.2f", d)
    }

    /// Format an exposure value as EV stops (e.g. `+0.67 EV`).
    private static func formatEV(_ d: Double) -> String {
        if abs(d) < 0.005 { return "0.00" }
        return String(format: "%+.2f", d)
    }
}